package main.java.gui;

import main.java.application.YearBudget;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

public class DisplayAllSpendingGUI extends JFrame {

    private JTable table;
    private JScrollPane scrollPane;
    private JPanel panel;
    private JLabel titleLabel;
    private JTextPane totalSpendingPane;

    public DisplayAllSpendingGUI(YearBudget yearReference) {
        super("All Spending Summary");
        System.out.println("INSIDE DisplayAllSpendingGUI");

        // display total spending
        totalSpendingPane.setText("Total Spending: " + yearReference.getYearlySpending().toString());
        // create and display table
        table.setModel(getCategoryTable(yearReference));

        setContentPane(panel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Accepts hashMap<String, Double> and returns it as a 2D array
     *
     * @return categorySpendingArr - array with categories as col 0 and total price as col 1
     */

    public String[][] hashMapTo2DArray(HashMap<String, Double> categorySpendingHashMap) {
        String[][] categorySpendingArr = new String[categorySpendingHashMap.size()][2];
        int row = 0;

        for (Map.Entry<String, Double> categorySpendingEntry : categorySpendingHashMap.entrySet()) {
            categorySpendingArr[row][0] = categorySpendingEntry.getKey();
            categorySpendingArr[row][1] = categorySpendingEntry.getValue().toString();
            row++;
        }
        return categorySpendingArr;
    }

    public TableModel getCategoryTable(YearBudget yearReference) {

        HashMap<String, Double> yearCategorySpendingHash = yearReference.getYearlyCategorySpending();
        String[][] yearCategorySpendingStrArr = hashMapTo2DArray(yearCategorySpendingHash);//new String[yearCategorySpending.size()][2];

        TableModel dataModel = new

                AbstractTableModel() {

                    @Override
                    public String getColumnName(int column) {

                        if (column == 0) {
                            return "Category";
                        } else {
                            return "Total Spending";
                        }
                    }

                    public int getColumnCount() {
                        return 2;
                    }

                    public int getRowCount() {
                        return yearCategorySpendingStrArr.length;
                    }

                    public Object getValueAt(int row, int col) {
                        return yearCategorySpendingStrArr[row][col];
                    }
                };

        return dataModel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane = new JScrollPane();
        panel.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table = new JTable();
        scrollPane.setViewportView(table);
        titleLabel = new JLabel();
        titleLabel.setText("Year Spending Summary");
        panel.add(titleLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        totalSpendingPane = new JTextPane();
        totalSpendingPane.setEditable(false);
        totalSpendingPane.setText("");
        panel.add(totalSpendingPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 25), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}